* Ability Tables
** Character Abilities Table

|---------------+---------------|
| Ability Score | Bonus/Penalty |
|---------------+---------------|
|             3 |            -3 |
|           4-5 |            -2 |
|           6-8 |            -1 |
|          9-12 |             0 |
|         13-15 |            +1 |
|         16-17 |            +2 |
|            18 |            +3 |
|---------------+---------------|

* Race Charts
** Dwarf Chart

Dwarves:
- Description
+ Dwarves are a short, stocky race; both male and female Dwarves stand around four feet tall and typically weigh around 120 pounds.
+ Their long hair and thick beards are dark brown, gray or black.
+ They take great pride in their beards, sometimes braiding or forking them.
+ They have a fair to ruddy complexion.
+ Dwarves have stout frames and a strong, muscular build.
+ They are rugged and resilient, with the capacity to endure great hardships.
+ Dwarves are typically practical, stubborn and courageous.
+ They can also be introspective, suspicious and possessive.
+ They have a lifespan of three to four centuries.

- Restrictions:
+ Dwarves may become Clerics, Fighters, or Thieves.
+ They are required to have a minimum Constitution of 9.
+ Due to their generally dour dispositions, they may not have a Charisma higher than 17.
+ They may not employ Large weapons more than four feet in length (specifically, two-handed swords, polearms, and longbows).

- Special Abilities:
+ All Dwarves have Darkvision with a 60' range, and are able to detect slanting passages, traps, shifting walls and new construction on a roll of 1-2 on 1d6; a search must be performed before this roll may be made

- Saving Throws:
+ Dwarves save at +4 vs. Death Ray or Poison, Magic Wands, Paralysis or Petrify, and Spells, and at +3 vs. Dragon Breath

** Elf Chart
Elves:
- Description:
+ Elves are a slender race, with both genders standing around five feet tall and weighing around 130 pounds.
+ Most have dark hair, with little or no body or facial hair.
+ Their skin is pale, and they have pointed ears and delicate features.
+ Elves are lithe and graceful.
+ They have keen eyesight and hearing.
+ Elves are typically inquisitive, passionate, self-assured, and sometimes haughty.
+ Their typical lifespan is a dozen centuries or more.

- Restrictions:
+ Elves may become Clerics, Fighters, Magic-Users or Thieves;
+ they are also allowed to combine the classes of Fighter and Magic-User, and of Magic-User and Thief (see Combination Classes, below).
+ They are required to have a minimum Intelligence of 9.
+ Due to their generally delicate nature, they may not have a Constitution higher than 17.
+ Elves never roll larger than six-sided dice (d6) for hit points.

- Special Abilities:
+ All Elves have Darkvision with a 60' range.
+ They are able to find secret doors more often than normal (1-2 on 1d6 rather than the usual 1 on 1d6).
+ An Elf is so observant that one has a 1 on 1d6 chance to find a secret door with a cursory look.
+ Elves are immune to the paralyzing attack of ghouls. Also, they are less likely to be surprised in combat, reducing the chance of surprise by 1 in 1d6.

- Saving Throws:
+ Elves save at +1 vs. Paralysis or Petrify, and +2 vs. Magic Wands and Spells
** Halflings Chart
Halflings:
- Description:
+ Halflings are small, slightly stocky folk who stand around three feet tall and weigh about 60 pounds.
+ They have curly brown hair on their heads and feet, but rarely have facial hair.
+ They are usually fair skinned, often with ruddy cheeks.
+ Halflings are remarkably rugged for their small size.
+ They are dexterous and nimble, capable of moving quietly and remaining very still.
+ They usually go barefoot.
+ Halflings are typically outgoing, unassuming and good-natured.
+ They live about a hundred years.

- Restrictions:
+ Halflings may become Clerics, Fighters or Thieves.
+ They are required to have a minimum Dexterity of 9.
+ Due to their small stature, they may not have a Strength higher than 17.
+ Halflings never roll larger than six-sided dice (d6) for hit points regardless of class.
+ Halflings may not use Large weapons, and must wield Medium weapons with both hands.

- Special Abilities:
+ Halflings are unusually accurate with all sorts of ranged weapons, gaining a +1 attack bonus when employing them.
+ When attacked in melee by creatures larger than man-sized, Halflings gain a +2 bonus to their Armor Class.
+ Halflings are quick-witted, thus adding +1 to Initiative die rolls.
+ Outdoors in their preferred forest terrain, they are able to hide very effectively; so long as they remain still there is only a 10% chance they will be detected.
+ Even indoors, in dungeons or in non-preferred terrain they are able to hide such that there is only a 30% chance of detection.
+ Note that a Halfling Thief will roll only once, using either the Thief ability or the Halfling ability, whichever is better.

- Saving Throws:
+ Halflings save at +4 vs. Death Ray or Poison, Magic Wands, Paralysis or Petrify, and Spells, and at +3 vs. Dragon Breath.

** Humans Chart
Humans:
- Description:
+ Humans come in a broad variety of shapes and sizes; the Game Master must decide what sorts of Humans live in the game world.
+ An average Human male in good health stands around six feet tall and weighs about 175 pounds.
+ Most Humans live around 75 years.

- Restrictions:
+ Humans may be any single class.
+ They have no minimum or maximum ability score requirements.

- Special Abilities:
+ Humans learn unusually quickly, gaining a bonus of 10% to all experience points earned.

- Saving Throws:
+ Humans are the “standard,” and thus have no saving throw bonuses

* Classes
** Combination Classes
*** Combination Classes Chart
- Requirements:
+ To become a member of a combination class, a character must meet the requirements of both classes.
+ Combination class characters use the best attack bonus and the best saving throw values of their original two classes, but must gain experience equal to the combined requirements of both base classes to advance in levels.
+ Elves are the only characters eligible to be a member of one of these combination classes:

- Fighter/Magic-User:
+ These characters may both fight and cast magic spells;
+ further, they are allowed to cast magic spells while wearing armor.
+ These characters roll six-sided dice (d6) for hit points.

- Magic-User/Thief:
+ Members of this combination class may cast spells while wearing leather armor, and may use any weapon.
+ These characters roll four-sided dice (d4) for hit points.

** Cleric
*** Cleric Background
- Cleric Background:
+ Clerics are those who have devoted themselves to the service of a deity, pantheon or other belief system.
+ Most Clerics spend their time in mundane forms of service such as preaching and ministering in a temple; but there are those who are called to go abroad from the temple and serve their deity in a more direct way, smiting undead monsters and aiding in the battle against evil and chaos.
+ Player character Clerics are assumed to be among the latter group.
+ Clerics fight about as well as Thieves, but not as well as Fighters.
+ They are hardier than Thieves, at least at lower levels, as they are accustomed to physical labor that the Thief would deftly avoid.
+ Clerics can cast spells of divine nature starting at 2nd level, and they have the power to Turn the Undead, that is, to drive away undead monsters by means of faith alone (see the Encounter section for details).
+ The Prime Requisite for Clerics is Wisdom; a character must have a Wisdom score of 9 or higher to become a Cleric.
+ They may wear any armor, but may only use blunt weapons (specifically including warhammer, mace, maul, club, quarterstaff, and sling).

*** Cleric Table
Cleric Table:

|-------+------------------+----------+--------+---+---+---+---+---|
|       |                  |          | Spells |   |   |   |   |   |
|-------+------------------+----------+--------+---+---+---+---+---|
| Level | Exp Points       | Hit Dice |      1 | 2 | 3 | 4 | 5 | 6 |
|-------+------------------+----------+--------+---+---+---+---+---|
|     1 | 0                |      1d6 |      - | - | - | - | - | - |
|     2 | 1,500            |      2d6 |      1 | - | - | - | - | - |
|     3 | 3,000            |      3d6 |      2 | - | - | - | - | - |
|     4 | 6,000            |      4d6 |      2 | 1 | - | - | - | - |
|     5 | 12,000           |      5d6 |      2 | 2 | - | - | - | - |
|     6 | 24,000           |      6d6 |      2 | 2 | 1 | - | - | - |
|     7 | 48,000           |      7d6 |      3 | 2 | 2 | - | - | - |
|     8 | 90,000           |      8d6 |      3 | 2 | 2 | 1 | - | - |
|     9 | 180,000          |      9d6 |      3 | 3 | 2 | 2 | - | - |
|    10 | 270,000          |    9d6+1 |      3 | 3 | 2 | 2 | 1 | - |
|    11 | 360,000          |    9d6+2 |      4 | 3 | 3 | 2 | 2 | - |
|    12 | 450,000          |    9d6+3 |      4 | 4 | 3 | 2 | 2 | 1 |
|    13 | 540,000          |    9d6+4 |      4 | 4 | 3 | 3 | 2 | 2 |
|    14 | 630,000          |    9d6+5 |      4 | 4 | 4 | 3 | 2 | 2 |
|    15 | 720,000          |    9d6+6 |      4 | 4 | 4 | 3 | 3 | 2 |
|    16 | 810,000          |    9d6+7 |      5 | 4 | 4 | 3 | 3 | 2 |
|    17 | 900,000          |    9d6+8 |      5 | 5 | 4 | 3 | 3 | 2 |
|    18 | 990,000          |    9d6+9 |      5 | 5 | 4 | 4 | 3 | 3 |
|    19 | 1,080,000 9d6+10 |        6 |      5 | 4 | 4 | 3 | 3 |   |
|    20 | 1,170,000 9d6+11 |        6 |      5 | 5 | 4 | 3 | 3 |   |
|-------+------------------+----------+--------+---+---+---+---+---|

** Fighter
*** Fighter Background
- Fighter Background:
+ Fighters include soldiers, guardsmen, barbarian warriors, and anyone else for whom fighting is a way of life.
+ They train in combat, and they generally approach problems head on, weapon drawn.
+ Not surprisingly, Fighters are best at fighting of all the classes.
+ They are also the hardiest, able to take more punishment than any other class.
+ Although they are not skilled in the ways of magic, Fighters can nonetheless use many magic items, including but not limited to magical weapons and armor.
+ The Prime Requisite for Fighters is Strength; a character must have a Strength score of 9 or higher to become a Fighter.
+ Members of this class may wear any armor and use any weapon.
*** Fighter Table
Fighter Table:

|-------+-----------+----------|
| Level | Points    | Hit Dice |
|-------+-----------+----------|
|     1 | 0         |      1d8 |
|     2 | 2,000     |      2d8 |
|     3 | 4,000     |      3d8 |
|     4 | 8,000     |      4d8 |
|     5 | 16,000    |      5d8 |
|     6 | 32,000    |      6d8 |
|     7 | 64,000    |      7d8 |
|     8 | 120,000   |      8d8 |
|     9 | 240,000   |      9d8 |
|    10 | 360,000   |    9d8+2 |
|    11 | 480,000   |    9d8+4 |
|    12 | 600,000   |    9d8+6 |
|    13 | 720,000   |    9d8+8 |
|    14 | 840,000   |   9d8+10 |
|    15 | 960,000   |   9d8+12 |
|    16 | 1,080,000 |   9d8+14 |
|    17 | 1,200,000 |   9d8+16 |
|    18 | 1,320,000 |   9d8+18 |
|    19 | 1,440,000 |   9d8+20 |
|    20 | 1,560,000 |   9d8+22 |
|-------+-----------+----------|

** Magic User
*** Magic-User Background
- Magic-User Background:
+ Magic-Users are those who seek and use knowledge of the arcane.
+ They do magic not as the Cleric does, by faith in a greater power, but rather through insight and understanding.
+ Magic-Users are the worst of all the classes at fighting;
+ hours spent studying massive tomes of magic do not lead a character to become strong or adept with weapons.
+ They are the least hardy, equal to Thieves at lower levels but quickly falling behind.
+ The Prime Requisite for Magic-Users is Intelligence;
+ a character must have an Intelligence score of 9 or higher to become a Magic-User.
+ The only weapons they become proficient with are the dagger and the walking staff (or cudgel).
+ Magic-Users may not wear armor of any sort nor use a shield as such things interfere with spellcasting.
+ A first level Magic-User begins play knowing read magic and one other spell of first level.
+ These spells are written in a spellbook provided by his or her master.
+ The GM may roll for the spell, assign it as he or she sees fit, or allow the player to choose it, at his or her option.
+ See the Spells section for more details

*** Magic-User Table
Magic-User Table:

|-------+------------+----------+--------+---+---+---+---+---|
|       |            |          | Spells |   |   |   |   |   |
|-------+------------+----------+--------+---+---+---+---+---|
| Level | Exp Points | Hit Dice |      1 | 2 | 3 | 4 | 5 | 6 |
|-------+------------+----------+--------+---+---+---+---+---|
|     1 | 0          |      1d4 |      1 | - | - | - | - | - |
|     2 | 2,500      |      2d4 |      2 | - | - | - | - | - |
|     3 | 5,000      |      3d4 |      2 | 1 | - | - | - | - |
|     4 | 10,000     |      4d4 |      2 | 2 | - | - | - | - |
|     5 | 20,000     |      5d4 |      2 | 2 | 1 | - | - | - |
|     6 | 40,000     |      6d4 |      3 | 2 | 2 | - | - | - |
|     7 | 80,000     |      7d4 |      3 | 2 | 2 | 1 | - | - |
|     8 | 150,000    |      8d4 |      3 | 3 | 2 | 2 | - | - |
|     9 | 300,000    |      9d4 |      3 | 3 | 2 | 2 | 1 | - |
|    10 | 450,000    |    9d4+1 |      4 | 3 | 3 | 2 | 2 | - |
|    11 | 600,000    |    9d4+2 |      4 | 4 | 3 | 2 | 2 | 1 |
|    12 | 750,000    |    9d4+3 |      4 | 4 | 3 | 3 | 2 | 2 |
|    13 | 900,000    |    9d4+4 |      4 | 4 | 4 | 3 | 2 | 2 |
|    14 | 1,050,000  |    9d4+5 |      4 | 4 | 4 | 3 | 3 | 2 |
|    15 | 1,200,000  |    9d4+6 |      5 | 4 | 4 | 3 | 3 | 2 |
|    16 | 1,350,000  |    9d4+7 |      5 | 5 | 4 | 3 | 3 | 2 |
|    17 | 1,500,000  |    9d4+8 |      5 | 5 | 4 | 4 | 3 | 3 |
|    18 | 1,650,000  |    9d4+9 |      6 | 5 | 4 | 4 | 3 | 3 |
|    19 | 1,800,000  |   9d4+10 |      6 | 5 | 5 | 4 | 3 | 3 |
|    20 | 1,950,000  |   9d4+11 |      6 | 5 | 5 | 4 | 4 | 3 |
|-------+------------+----------+--------+---+---+---+---+---|

** Thief
*** Thief Background
- Thief Background:
+ Thieves are those who take what they want or need by stealth, disarming traps and picking locks to get to the gold they crave;
+ or “borrowing” money from pockets, beltpouches, etc. right under the nose of the “mark” without the victim ever knowing.
+ Thieves fight better than Magic-Users but not as well as Fighters.
+ Avoidance of honest work leads Thieves to be less hardy than the other classes, though they do pull ahead of the Magic-Users at higher levels.
+ The Prime Requisite for Thieves is Dexterity;
+ a character must have a Dexterity score of 9 or higher to become a Thief.
+ They may use any weapon, but may not wear metal armor as it interferes with stealthy activities, nor may they use shields of any sort.
+ Leather armor is acceptable, however.
+ Thieves have a number of special abilities, described below.
+ One Turn must generally be spent to use any of these abilities, though the GM may amend this as he or she sees fit.
+ The GM may choose to make any of these rolls on behalf of the player, at his or her option, to help maintain the proper state of uncertainty.
+ Also note that the GM may apply situational adjustments (plus or minus percentage points) as he or she sees fit; for instance, it's obviously harder to climb a wall slick with slime than one that is dry, so the GM might apply a penalty of 20% for the slimy wall

*** Thief Table
Thief Table:

|-------+---------+---------|
| Level | Points  | HitDice |
|-------+---------+---------|
|     1 | 0       |     1d4 |
|     2 | 1,250   |     2d4 |
|     3 | 2,500   |     3d4 |
|     4 | 5,000   |     4d4 |
|     5 | 10,000  |     5d4 |
|     6 | 20,000  |     6d4 |
|     7 | 40,000  |     7d4 |
|     8 | 75,000  |     8d4 |
|     9 | 150,000 |     9d4 |
|    10 | 225,000 |   9d4+2 |
|    11 | 300,000 |   9d4+4 |
|    12 | 375,000 |   9d4+6 |
|    13 | 450,000 |   9d4+8 |
|    14 | 525,000 |  9d4+10 |
|    15 | 600,000 |  9d4+12 |
|    16 | 675,000 |  9d4+14 |
|    17 | 750,000 |  9d4+16 |
|    18 | 825,000 |  9d4+18 |
|    19 | 900,000 |  9d4+20 |
|    20 | 975,000 |  9d4+22 |
|-------+---------+---------|
*** Thief Abilities Background
Thief Abilities Background:

- Open Locks
+ allows the Thief to unlock a lock without a proper key.
+ It may only be tried once per lock.
+ If the attempt fails, the Thief must wait until he or she has gained another level of experience before trying again.

- Remove Traps
+ is generally rolled twice:
+ first to detect the trap, and second to disarm it.
+ The GM will make these rolls as the player won't know for sure if the character is successful or not until someone actually tests the trapped (or suspected) area.

- Pick Pockets
+ allows the Thief to lift the wallet, cut the purse, etc. of a victim without the victim noticing.
+ Obviously, if the roll is failed, the Thief didn't get what he or she wanted; but further, the intended victim (or an onlooker, at the GM's option) will notice the attempt if the die roll is more than two times the target number (or if the die roll is 00).

- Move Silently
+ like Remove Traps, is always rolled by the GM.
+ The Thief will usually believe he or she is moving silently regardless of the die roll, but those he or she is trying to avoid will hear the Thief if the roll is failed.

- Climb Walls
+ permits the Thief to climb sheer surfaces with few or no visible handholds.
+ This ability should normally be rolled by the player.
+ If the roll fails, the Thief falls from about halfway up the wall or other vertical surface.
+ The GM may require multiple rolls if the distance climbed is more than 100 feet

- Hide
+ permits the Thief to hide in any shadowed area large enough to contain his or her body.
+ Like Move Silently, the Thief always believes he or she is being successful, so the GM makes the roll.
+ A Thief hiding in shadows must remain still for this ability to work.

- Listen
+ is generally used to listen at a door, or to try to listen for distant sounds in a dungeon.
+ The GM must decide what noises the Thief might hear;
+ a successful roll means only that a noise could have been heard.
+ The GM should always make this roll for the player.
+ Note that the Thief and his or her party must try to be quiet in order for the Thief to use this ability.
+ Finally, Thieves can perform a Sneak Attack any time they are behind an opponent in melee and it is reasonably likely the opponent doesn't know the Thief is there.
+ The GM may require a Move Silently or Hide roll to determine this.

- Sneak Attack
+ made with a +4 attack bonus and does double damage if it is successful.
+ A Thief usually can't make a Sneak Attack on the same opponent twice in any given combat.
+ The Sneak Attack can be performed with any melee (but not missile) weapon, or may be performed bare-handed (in which case subduing damage is done; see the Encounter section for details).
+ Also, the Sneak Attack can be performed with the “flat of the blade;” the bonuses and penalties cancel out, so the attack has a +0 attack bonus and does normal damage;
+ the damage done in this case is subduing damage.

*** Thief Abilities Table

Thief Abilities Table:

|-------------+------------+--------------+--------------+---------------+-------------+------+--------|
| Thief Level | Open Locks | Remove Traps | Pick Pockets | Move Silently | Climb Walls | Hide | Listen |
|-------------+------------+--------------+--------------+---------------+-------------+------+--------|
|           1 |         25 |           20 |           30 |            25 |          80 |   10 |     30 |
|           2 |         30 |           25 |           35 |            30 |          81 |   15 |     34 |
|           3 |         35 |           30 |           40 |            35 |          82 |   20 |     38 |
|           4 |         40 |           35 |           45 |            40 |          83 |   25 |     42 |
|           5 |         45 |           40 |           50 |            45 |          84 |   30 |     46 |
|           6 |         50 |           45 |           55 |            50 |          85 |   35 |     50 |
|           7 |         55 |           50 |           60 |            55 |          86 |   40 |     54 |
|           8 |         60 |           55 |           65 |            60 |          87 |   45 |     58 |
|           9 |         65 |           60 |           70 |            65 |          88 |   50 |     62 |
|          10 |         68 |           63 |           74 |            68 |          89 |   53 |     65 |
|          11 |         71 |           66 |           78 |            71 |          90 |   56 |     68 |
|          12 |         74 |           69 |           82 |            74 |          91 |   59 |     71 |
|          13 |         77 |           72 |           86 |            77 |          92 |   62 |     74 |
|          14 |         80 |           75 |           90 |            80 |          93 |   65 |     77 |
|          15 |         83 |           78 |           94 |            83 |          94 |   68 |     80 |
|          16 |         84 |           79 |           95 |            85 |          95 |   69 |     83 |
|          17 |         85 |           80 |           96 |            87 |          96 |   70 |     86 |
|          18 |         86 |           81 |           97 |            89 |          97 |   71 |     89 |
|          19 |         87 |           82 |           98 |            91 |          98 |   72 |     92 |
|          20 |         88 |           83 |           99 |            93 |          99 |   73 |     95 |
|-------------+------------+--------------+--------------+---------------+-------------+------+--------|
